# creation rules are evaluated sequentially, the first match wins
# AGE: age-keygen -o key.txt (then place in the sops config)
# see: https://github.com/mozilla/sops#22encrypting-using-age)
creation_rules:
        - path_regex: secret.*\.yaml$
          age: >-
            age105uc5039exdle33ewpwqtjt8hpk5ex7gchuvv2uqdjq7n7kypgzsptuvqm
